### ISSUE TITLE
CLI installation not working

### ISSUE THREAD

**Issue by fredguth** [earthstar-project/earthstar#261]
## What's the problem you want solved?
When trying to follow instructions from `https://earthstar-project.org/get-started/install-cli`, there is an error and the cli does not install.

command:
`deno install --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts`

error:
`error: Module not found "https://deno.land/x/crayon/types.ts".
    at https://deno.land/x/crayon_chalk_aliases@1.1.0/index.ts:8:24
`

```
❯ deno --version
deno 1.23.1 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

## Is there a solution you'd like to recommend?
🤷

**Comment by achou11** [comment]
chalk should've been removed in v9.3.3 although there are a couple of references to it:

https://github.com/earthstar-project/earthstar/blob/54860154e8f85528f1a533f1b56604c20ad00860/depchart/depchart-deps.dot#L169

https://github.com/earthstar-project/earthstar/blob/54860154e8f85528f1a533f1b56604c20ad00860/depchart/depchart-deps.dot#L270

this file looks like a dev-only tool (basically only generated from a make command called manually), so curious as to how this is causing issues if it is

**Comment by tfvg** [comment]
Hello there
The problem seems to be 
Warning Implicitly using latest version (3.3.1) for https://deno.land/x/crayon/types.ts

which has a completely different interface than v2 which messes crayon_chalk_aliases up

So, I tried forcing v2 by using an import map, creating a file named importmap.json as follows

{
  "imports": {
    "https://deno.land/x/crayon/": "https://deno.land/x/crayon@2.3.1/"
  }
}

and telling deno to use that

$ deno install --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar --import-map=importmap.json  https://deno.land/x/earthstar_cli/src/main.ts

result
✅ Successfully installed earthstar

HTH

**Comment by sgwilym** [comment]
Crayon had some kind of breaking change before I left on holiday, which was reported in #258 and fixed in #260.

Unfortunately I forgot to update the version of earthstar which earthstar-cli relies on. This has been now been done and the original installation commands should work.

@achou11 and @tfvg thanks for pitching in and offering alternative solutions!

Stuff like this is one reason I'm tempted to put earthstar core, CLI, and replica server code all in one repository.

**Comment by fredguth** [comment]
Same command?
`deno install --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts`

**Comment by sgwilym** [comment]
@fredguth Yes. Is it still giving you trouble?

**Comment by fredguth** [comment]
Yep:

```
 ❯ deno install --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts
Download https://deno.land/x/crayon/types.ts
Warning Implicitly using latest version (3.3.2) for https://deno.land/x/crayon/types.ts
Download https://deno.land/x/crayon@3.3.2/types.ts
error: Module not found "https://deno.land/x/crayon/types.ts".
    at https://deno.land/x/crayon_chalk_aliases@1.1.0/types.ts:1:41
    
```

```

 ❯ deno --version
deno 1.23.1 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

**Comment by sgwilym** [comment]
Hey all, could you run the following: 

```
deno install --reload --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts
```

and let me know happens? I've added a `--reload` flag there to force Deno not to use any cached version of `https://deno.land/x/earthstar_cli/src/main.ts` which may be present on your system.
