### ISSUE TITLE
Unclear how to use "earthstar identities switch"

### ISSUE THREAD

**Issue by decentral1se** [earthstar-project/earthstar#277]
## What's the problem you want solved?

```
earthstar identities list
┌─────────────────────────────────────────────────────────────┬──────────┐
│ Address                                                     │ Selected │
├─────────────────────────────────────────────────────────────┼──────────┤
│ @foob.bufxdf5jjo2jd5p3tz47byl564h4nye2tq7hlh7dn3hfbtro6nebq │          │
└─────────────────────────────────────────────────────────────┴──────────┘
```

```
earthstar identities switch
 ? Select which identity to use to sign documentserror: Uncaught TypeError: Deno.setRaw is not a function
      (Deno.setRaw as setRaw)(yl564h4nye2tq7hlh7dn3hfbtro6nebq
                             ^
    at Select.#readChar (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_prompt.ts:285:30)
    at Select.#readKey (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_prompt.ts:273:50)
    at Select.read (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_prompt.ts:169:52)
    at Select.read (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_list.ts:254:18)
    at Select.#execute (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_prompt.ts:111:21)
    at async Select.prompt (https://deno.land/x/cliffy@v0.22.2/prompt/_generic_prompt.ts:90:14)
    at async Command.fn (https://deno.land/x/earthstar_cli@8.3.5/src/identity.ts:146:33)
    at async Command.execute (https://deno.land/x/cliffy@v0.22.2/command/command.ts:1026:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.22.2/command/command.ts:940:16)
    at async https://deno.land/x/earthstar_cli@8.3.5/src/main.ts:23:1
```

```
earthstar identities switch foob

  Usage:   earthstar identities switch
  Version: v8.3.5                     

  Description:

    Set the current identity

  Options:

    -h, --help  - Show this help.  

  error: No arguments allowed for command "earthstar identities switch".
```

## Is there a solution you'd like to recommend?

I can pass the shortname as an arg? e.g. `foob`

**Comment by achou11** [comment]
this should probably be moved to https://github.com/earthstar/earthstar-cli

**Comment by achou11** [comment]
couple of issues to note, one of which has already been reported :)

https://github.com/earthstar-project/earthstar-cli/issues/22

as for usage issues, think there's been some early discussions about redesigning the cli to be simpler and more straightforward, but good to point out things like this too!

**Comment by sgwilym** [comment]
Going to close this, discussion is at https://github.com/earthstar-project/earthstar-cli/issues/22
